version: "3"
services:
    insert:
        image: pachecowillians/get-one:latest
        ports:
            - "3332:3332"
        env_file:
            - ../.env
        deploy:
            replicas: 2
            placement:
                constraints: [node.role==worker]
